### PR TITLE
initial rule overrides for discussion

### PR DESCRIPTION
**Pull request by Ollo**

### CODE REVIEW

**Comment by matthopson** [comment]
@Ollo  I've got some of these already covered here: https://github.com/teamsnap/javascript/pull/1/files

**Comment by Ollo** [comment]
yeah realized that after I got it pulled down and made changes

**Comment by Ollo** [comment]
Mine I believe only has the addition of the `'jsx-closing-bracket-location'`

**Comment by matthopson** [comment]
If you want to just throw that on that branch, you can. I like having the link / description of what the feature does so we can discuss it.

**Comment by Ollo** [comment]
adding the alignment rule and links to docs to matts pr.. closing

**Pull request closed without merging**
